baseURL = "https://4skin.netlify.com"
disqusShortname = ""
languageCode = "en-us"
languageName = "En"
paginate = "5"
theme = "4Skin4Life"
title = "4Skin4Life"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Inquiries"
url = "Rumple@4skin.monster"
weight = 5
[[menu.main]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 4
[[menu.main]]
name = "Category"
url = "categories/nature/"
weight = 3
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "More Information at [Intaction](https://intaction.org/) & [Your Whole Baby](https://yourwholebaby.org)"
description = "This is meta description"
logo = "images/logo.png"
search = true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
